### ISSUE TITLE
Cover the `RetryUtil.java` class by Unit tests

### ISSUE THREAD

**Issue by andrii-bodnar** [crowdin/android-studio-plugin#86]
The `RetryUtil.java` class has no Unit test coverage. It would be great to add Unit tests for this class.

[Actual coverage](https://app.codecov.io/gh/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/RetryUtil.java)
[RetryUtil.java](https://github.com/crowdin/android-studio-plugin/blob/master/src/main/java/com/crowdin/util/RetryUtil.java)

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
Can I work on this?

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
I noticed that there's a part of the code n RetryUtil.java which will never get called.
Line 23 throw e gets called when i+i==retries.
Since retries is an odd number 3 and it is a private static final variable which means it can't be changed so it's not possible for the i+i==retries condition to ever be true as i is integer.
Should I remove this part of the code from the file?

**Comment by andrii-bodnar** [comment]
@Sakshi-75 nice catch! I would suggest changing this condition in the following way: `i + 1 == retries`

**Comment by Sakshi-75** [comment]
Hi @andrii-bodnar ,
I've raised a PR for this: https://github.com/crowdin/android-studio-plugin/pull/88
Please review it.
